#dz-16-17 Another tasks and calc
nikikozyrev/dz-js-basic pull request #5
Opened 2024-08-13 08:35 UTC by nikikozyrev

2024-08-14 11:21 UTC, GitEsense requested changes
Вы не должны создавать новый объект и методы в нём, по сути Вы должны лишь переиспользовать существующие с передачей контекста.

По "калькулятору" - воспользуйтесь всплытием событий

2024-08-16 06:49 UTC, nikikozyrev commented
1) По another-task: я уже и лекции пересмотрел, и задание переслушал, и всё равно не понимаю, как именно нужно сделать. Что значит "не должны создавать новый объект и методы в нём, по сути Вы должны лишь переиспользовать существующие с передачей контекста"? Получается новый объект нужен, к нему же нужно привязать контекст. Разъясните чуть чуть, пожалуйста)

2) По калькулятору: я конечно могу разобраться и почитать про всплытие событий, но они изучаются уже в продвинутом JS в одном из последних модулей.

2024-08-16 06:57 UTC, GitEsense commented
> 1. По another-task: я уже и лекции пересмотрел, и задание переслушал, и всё равно не понимаю, как именно нужно сделать. Что значит "не должны создавать новый объект и методы в нём, по сути Вы должны лишь переиспользовать существующие с передачей контекста"? Получается новый объект нужен, к нему же нужно привязать контекст. Разъясните чуть чуть, пожалуйста)
> 2. По калькулятору: я конечно могу разобраться и почитать про всплытие событий, но они изучаются уже в продвинутом JS в одном из последних модулей.

1. Разумеется Вы создаёте новый объект newTask , но методы в нем не дублируете, если хотите добавить задачу в newTask - Вы должны использовать методы toDoList , а т.к. методы у нас там работают с this, то и контекст должен быть передан подходящий 

2. Всплытие событий - это event click/change и т.п. - это в рамках DOM можно реализовать, тут это не требование, а рекомендация

2024-08-19 08:13 UTC, GitEsense requested changes
Осталось немножко доработать)

2024-08-19 08:13 UTC, GitEsense commented on 16-another-tasks/index.js
> +addTask("Сделать домашку", 8);
а как нам добавить параметр description для какой-либо задачи? кроме как объявление "вручную" при инициализации?

Можете реализовать исходные методы через работу с объектом (речь про add и update) - тогда всё станет сильно проще (что если у нас в задаче например будет 50 свойств и плюс вложенность? как нам с этим работать? даже если это будет задача вида
```js
const task = {
    id: 22,
    description: 'Обязательно обратить внимание на условия выполнения',
    title: "Внесение критических изменений",
    conditions: [
        'Решение должно быть масштабируемым',
        'Должны быть реализованы проверки данных',
        'Обязательно присутствуют тесты'
    ],
    users: [
        { 
            id: 2, 
            role: ['manager', 'moderator'], 
            name: 'Олег', 
            surname: 'Сидоров', 
            lastname: 'Петрович' 
        },
        { 
            id: 4, 
            role: ['administrator'], 
            name: 'Иван', 
            surname: 'Иванов', 
            lastname: 'Иванович' 
        }
    ]
}
```

2024-08-19 08:14 UTC, GitEsense commented on 17-calc/app.js
> +}
Представляю для анализа и ознакомления реализацию через всплытие, а так же декомпозиция.

**JavaScript код для страницы:**
```js
'use strict';

const page = {
    buttons: document.querySelector('.buttons'),
    inputs: document.querySelector('.inputs'),
    answer: document.querySelector('.answer'),
    selectedAction: null,
}
let selectedOperation = '';

page.buttons.addEventListener('click', (event) => {
    if (event.target.tagName !== 'BUTTON') {
        return;
    }

    const btn = event.target;
    resetActiveButtons();
    selectedButton(btn);
})

function clearForm() {
    resetActiveButtons();
    resetInputs();
}
function resetInputs() {
    page.inputs.childNodes.forEach((input) => { input.value = '' });
}

function resetActiveButtons() {
    page.buttons.childNodes.forEach(button => {
        if (button.nodeName !== 'BUTTON') {
            return
        }
        button.classList.remove('button-active');
    });
    page.selectedAction = null;
}

function selectedButton(button) {
    button.classList.add('button-active');
    page.selectedAction = button.innerText;
}
function renderError(err, block = page.answer) {
    block.innerText = err
}
function renderResult(result, block = page.answer) {
    block.innerText = parseFloat(result)
    clearForm();
}

function calculate(a, b, char) {
    switch (char) {
        case '+': return a + b;
        case '-': return a - b;
        case '/': return b !== 0 ? a / b : 'Нельзя делить на ноль'
        case '*': return a * b;
    }
}

function submitForm() {
    const inputs = [...page.inputs.children]
    const [input1, input2] = inputs.map(x => Number(x.value));

    if (isNaN(input1) || !input1) {
        return renderError('Введите первое число');
    }
    if (isNaN(input2) || !input2) {
        return renderError('Введите второе число');
    }
    if (!page.selectedAction) {
        return renderError('Выберете операцию');
    }

    const result = calculate(input1, input2, page.selectedAction);

    renderResult(result);
};  
```

**Упрощённый HTML:**
```html
<body style="background-color: #1c1b21; text-align: center">
    <div class="calculator">
        <div class="inputs">
            <input class="input"></input>
            <input class="input"></input>
        </div>
        <div class="buttons">
            <button class="button">+</button>
            <button class="button">-</button>
            <button class="button">*</button>
            <button class="button">/</button>
        </div>
        <button class="button button-active" onclick="submitForm()">Посчитать</button>
        <div class="answerText">Ответ:</div>
        <div class="answer"></div>
    </div>

    <script src="./app.js"></script>
</body>
```

**Новый стиль CSS:**
```css
* {
    box-sizing: border-box;
}

body {
    color: white;
    font-size: 30px;
    line-height: 21px;
}

button {
    border-radius: 13px;
    font-size: 30px;
    line-height: 21px;
    outline: none;
    padding: 18px 24px
}

.button {
    background: rgba(255, 255, 255, 0.05);
    color: white;
    border: 1px solid rgba(212, 212, 212, 0.05);
}

.button:hover {
    background: rgba(255, 255, 255, 0.091);
}

.button-active {
    background: #6c38cc;
}

.button-active:hover {
    background: #844fe6;
}

.calculator {
    max-width: 480px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 10px;
    align-items: center;
}

.buttons,
.inputs {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
}

.input {
    box-sizing: border-box;
    padding: 15px 16px;
    color: white;
    border: 1px solid rgba(212, 212, 212, 0.05);
    background: rgba(255, 255, 255, 0.05);
    border-radius: 10px;
    font-size: 18px;
    line-height: 21px;
    outline: none;
}

.answerText {
    padding: 15px 16px;
}

.answer {
    width: 100%;
    min-height: 54px;
    padding: 15px;

    border: 1px solid rgba(212, 212, 212, 0.05);
    background: rgba(255, 255, 255, 0.05);
    border-radius: 10px;
    font-size: 26px;
}
```

2024-08-19 10:38 UTC, nikikozyrev commented on 16-another-tasks/index.js
> +addTask("Сделать домашку", 8);
Я, честно, в ступоре и не понимаю, как добавить description. В моём понимании, только если исходный метод изменить, чтобы он принимал description. А про add и update речь вообще не шла в курсе.

2024-08-19 10:56 UTC, GitEsense commented on 16-another-tasks/index.js
> +addTask("Сделать домашку", 8);
> Я, честно, в ступоре и не понимаю, как добавить description. В моём понимании, только если исходный метод изменить, чтобы он принимал description. А про add и update речь вообще не шла в курсе.

Поэтому и предлагаю реализацию через объект (т.е. передаём объект, а не title + priority) в качестве аргумента, в прочем - можно переиспользовать метод и расширить его, например
```js
newTask.addTask = function(title, priority, description) {
    const task = toDoList.addTask.call(newTask, title, priority);
    task.description = description;
}
```
Где всё-таки немного переделали (но логику, а не аргументы) в toDoList.addTask
```js
addTask(title, priority) {
        if (!title || !priority) {
            console.log("Введите заголовок и приоритет!");
            return;
        } 
        const task = {
            title,
            id: idCount(),
            priority,
        }
        this.tasks.push(task);
        return task;
        
    },
```

Вариантов множество, а на тему add и update - это речь про методы addTask / updateTask

2024-08-19 11:01 UTC, GitEsense commented on 16-another-tasks/index.js
> +addTask("Сделать домашку", 8);
> Я, честно, в ступоре и не понимаю, как добавить description. В моём понимании, только если исходный метод изменить, чтобы он принимал description. А про add и update речь вообще не шла в курсе.

Если же работать как с объектом, то у нас может быть всё "проще", т.е.
```js
    addTask(data) {
        const isValid = this.isValidData(data);
        if (!isValid) {
            return this;
        }
        if (!this.tasks) {
            this.tasks = [];
        }
        if (!this.lastId) {
            this.lastId = 0;
        }

        this.tasks.push({ ...data, id: ++this.lastId, createdAt: Date.now(), updatedAt: null });
        return this;
    },
```
Так бы выглядел метод (это пример) работы с объектом, тогда мы спокойно можем туда передать объект любой сложности и он будет записан
То же самое можно передать в "updateTask" и следовать правилу "слияния" объектов.

В задаче же идёт речь "переиспользовать методы", т.е. формально - да, всё отлично, но я всё-таки "предлагаю" именно научиться "запихивать" доп. свойство по необходимости (т.е. у нас есть условно taskManager), а какие именно задачи будут там хранится и с какими свойствами - уже будет не важно

Но почему не предлагаю "расширять" (т.е. записывать) методы - это лишь потому, что по-хорошему у нас newTask останется "без методов", т.е. мы наполняем, а при консоли newTask мы увидим, что там есть только массив tasks

2024-08-19 11:02 UTC, GitEsense commented on 16-another-tasks/index.js
> +addTask("Сделать домашку", 8);
Оставлю для анализа реализацию с несколькими update и несколькими add функциями
Первая add - классическая с объектом
Вторая add - через строковые параметры или объект

Первая update через передачу id и объекта
Вторая update через передачу объекта с id
```js
const toDoList = {
    tasks: [],
    isValidData(data) {
        if (!data) {
            console.log('Данные не переданы');
            return false;
        }
        if (typeof data !== 'object') {
            console.log('Переданные данные не являются объектом');
            return false;
        }
        return true;
    },
    getTaskById(taskId) {
        if(!taskId){
            console.log(`Значение ID не передано или передано некорректно`);
            return;
        }
        const task = this.tasks?.find(({ id }) => id === taskId) ?? null;
        if (!task) {
            console.log(`Задача с id ${ taskId } еще не добавлена в ваш список дел.`);
        }
        return task;
    },
    addTask(data) {
        const isValid = this.isValidData(data);
        if (!isValid) {
            return this;
        }
        if (!this.tasks) {
            this.tasks = [];
        }
        if (!this.lastId) {
            this.lastId = 0;
        }

        this.tasks.push({ ...data, id: ++this.lastId, createdAt: Date.now(), updatedAt: null });
        return this;
    },
    addTask2(...args) {
        const [title, priority, ...other] = args;
        const data = {};
        if (typeof title === 'string') {
            if (!title) {
                console.log('Тайтл не может быть пустым');
                return this;
            }
            if (!priority) {
                console.log('Приоритет не заполнен');
                return this;
            }
            data.title = title;
            data.priority = priority;
            if (other.length > 0) {
                data.descriptiion = [...other];
            }
        } else {
            const isValid = this.isValidData(title);
            if (!isValid) {
                return this;
            }
            Object.assign(data, title);
        }
        if (!this.tasks) {
            this.tasks = [];
        }
        if (!this.lastId) {
            this.lastId = 0;
        }

        this.tasks.push({ ...data, id: ++this.lastId, createdAt: Date.now(), updatedAt: null });
        return this;
    },
    removeTask: function (id) {
        const task = this.getTaskById(id);
        if (task) {
            console.log(`Задача с id ${ id } успешно удалена.`);
            this.tasks = this.tasks.filter((el) => el.id !== id);
        }
        return this;
    },

    updateTask(taskId, newData) {
        const { id, ...data } = newData;
        const isValid = this.isValidData(data);
        if (!isValid) {
            return this;
        }
        const task = this.getTaskById(taskId);

        if (task) {
            console.log(`Задача с id ${ taskId } успешно обновлена.`);
            Object.assign(task, { ...data, updatedAt: Date.now() });
        }
        return this;
    },
    updateTask2(newData) {
        const { id, ...data } = newData;
        const isValid = this.isValidData(data);
        if (!isValid) {
            return this;
        }
        const task = this.getTaskById(id);

        if (task) {
            console.log(`Задача с id ${ id } успешно обновлена.`);
            Object.assign(task, { ...newData, updatedAt: Date.now() });
        }
        return this;
    },

    sortTasks: function (desc = false, sortBy = 'id') {
        const ALLOW_KEYS = [...new Set(this.tasks.map(Object.keys).flat())];

        if (!ALLOW_KEYS.includes(sortBy)) {
            console.log(`Нет такого ключа, доступные ключи: [${ ALLOW_KEYS.join(', ') }]`);
            return;
        }

        this.tasks.sort(({ [sortBy]: a }, { [sortBy]: b }) => (desc ? b - a : a - b));
    },
};
```

2024-08-19 11:02 UTC, GitEsense approved these changes

2024-08-19 11:29 UTC, merged